name: Clone repository

on:
  workflow_call:
    inputs:
      repository:
        description: 'repository'
        required: true
        type: string
      target_branch:
        description: 'target branch'
        required: false
        default: 'master'
        type: string
      target_directory:
        description: 'target directory'
        required: false
        default: '.'
        type: string
      copy_list:
        description: 'list of files and directories to clone'
        required: true
        type: string

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: remove files
        shell: bash
        env:
          LIST: ${{inputs.copy_list}}
        run: |
          mkdir output
          for file in `echo $LIST`; do
            echo "processing $file"
            if [ -f "$file" ] || [ -d "$file" ]; then
              echo "$file exists"
              mv $file output/          
            fi
          done
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: output/
          destination-github-username: 'lsnova'
          destination-repository-name: ${{inputs.repository}}
          user-email: patryks@lsn.io
          target-directory: ${{inputs.target_directory}}
          target-branch: ${{inputs.target_branch}}
