name: Package build and deploy CI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - uses: whelk-io/maven-settings-xml-action@v20
        with:
          repositories: >
            [
              {
                "id": "github-maven-pkg",
                "url": "https://maven.pkg.github.com/lsnova/*",
                "snapshots": {
                  "enabled": "true"
                }
              }
            ]
          servers: >
            [
              {
                "id": "github-maven-pkg",
                "username": "${{ secrets.MAVEN_PKG_GITHUB_USERNAME }}",
                "password": "${{ secrets.MAVEN_PKG_GITHUB_PASSWORD }}"
              }
            ]
      - name: environment variables
        run: |
          echo "GIT_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "BUILD_DATE=$(date  +%F\ %T\ %Z)" >> $GITHUB_ENV
          echo "PACKAGE_NAME=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_ENV
          echo "PACKAGE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
        shell: bash
      - name: mvn package and deploy module
        run: |
          mvn clean package deploy -B -U
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: always()
        env:
          SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://github.com/lsnova.png?size=48
          SLACK_MESSAGE: ${{ env.PACKAGE_NAME }}:${{ env.PACKAGE_VERSION }}
          SLACK_FOOTER: lsn
          SLACK_TITLE: 'Package build and deploy'
          SLACK_USERNAME: github
