name: Package build and deploy CI

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github-maven-pkg
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: environment variables
        run: |
          echo "PACKAGE_NAME=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_ENV
          echo "PACKAGE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
        shell: bash
      - name: Publish package
        run: mvn -B -U clean deploy
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_PKG_GITHUB_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PKG_GITHUB_PASSWORD }}
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: always()
        env:
          SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://github.com/lsnova.png?size=48
          SLACK_MESSAGE: ${{ env.PACKAGE_NAME }}:${{ env.PACKAGE_VERSION }}
          SLACK_FOOTER: lsn
          SLACK_TITLE: 'Package build and deploy'
          SLACK_USERNAME: github
          MSG_MINIMAL: true
