name: Sonar scan (Java11)

on:
  workflow_call:
    inputs:
      precompile:
        description: 'precompile script'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.HEAD_REF }}
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: precompile bash
        if: "${{ inputs.precompile != '' }}"
        run: |
          sh ${{inputs.precompile}}
      - name: sonar
        env:
          SONAR_ORGANIZATION: ${{secrets.SONAR_ORGANIZATION}}
          SONARQUBE_TOKEN: ${{secrets.SONAR_TOKEN}}
          GITHUB_REF: ${ GITHUB_REF:11 }
        run: |
          mvn clean package sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONARQUBE_TOKEN -Dsonar.branch.name=$GITHUB_REF -Dsonar.scm.provider=git -Dsonar.java.binaries=target/classes -Dsonar.organization=$SONAR_ORGANIZATION
